import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navigation from "../components/main-header/navigation";
import Footer from "@/components/footer/footer";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Meds Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body className={inter.className}>
        <Navigation/>
        {children}
        <Footer/>
        </body>

    </html>
  );
}
